const appname = "eMarket";
const appversion = "Version 1.0.0";
const credits = "@DG";
const name = "Name";
const nameHint = "Name Surname";
const surname = "Surname";
const email = "e-Mail";
const emailHint = "name@name.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const forgetPass = "Forget Password";
const login = "Login";
const signup = "Sing-up";
const createNewAccount = "or, create a new account";
const loginWith = "Login with";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account? ";

const home = "Home", categories = "Categories", cart = "Cart", account = "Account";